services:

  web-app:
    build:
      context: ./app
    expose:
      - "8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp_password

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-app

  mysql:
    image: mysql:8.4

    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp_password
      MYSQL_ROOT_PASSWORD: root_password

    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uwebapp",
          "-pwebapp_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: